# Generated by Django 5.2 on 2025-04-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('blood_group', models.CharField(max_length=5)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('phonenumber', models.CharField(max_length=100, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('usertype', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=100)),
                ('bloodgroup', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
